from pathlib import Path  # Imports Path to locate the .env file containing the API key.
from dotenv import load_dotenv  # Loads environment variables stored inside the .env file.
from langchain_google_genai import ChatGoogleGenerativeAI  # Imports the Gemini chat model.
from langchain_core.prompts import ChatPromptTemplate  # Imports ChatPromptTemplate to create a reusable structured prompt.


env_path = Path(__file__).parent.parent / ".env"  # Locates the .env file in the main langchain-learning folder.
load_dotenv(env_path)  # Loads the Gemini API key from the .env file.


prompt = ChatPromptTemplate.from_messages([  # Creates a reusable chat prompt containing system and human messages.

    (
        "system",
        """You are a professional meeting preparation assistant.

Help the user prepare for an upcoming meeting.

Create a practical preparation brief containing:
- Meeting objective
- Key talking points
- Important questions to ask
- Potential concerns to prepare for
- Recommended communication approach

Keep the advice specific to the information provided.
Do not invent facts that were not provided by the user."""
    ),  # The system message defines the AI's role, responsibilities, and response expectations.

    (
        "human",
        """Meeting type: {meeting_type}

Meeting with: {audience}

Main objective: {objective}

Known context: {context}

Main concerns: {concerns}

Prepare me for this meeting."""
    )  # The human message uses multiple variables so the same prompt works for different meetings.
])


model = ChatGoogleGenerativeAI(
    model="gemini-3.8-flash"
)  # Creates the Gemini model that will generate the meeting preparation brief.


meeting_type = input("Meeting type: ")  # Collects the type of meeting, such as interview, client call, or performance review.
audience = input("Who are you meeting with? ")  # Collects information about the person or group attending the meeting.
objective = input("What is your main objective? ")  # Defines what the user wants to achieve during the meeting.
context = input("Provide the important context: ")  # Gives the model background information relevant to the meeting.
concerns = input("What are your main concerns? ")  # Identifies issues or difficult areas the user wants to prepare for.


formatted_prompt = prompt.invoke({  # Inserts the user's information into the variables inside ChatPromptTemplate.
    "meeting_type": meeting_type,
    "audience": audience,
    "objective": objective,
    "context": context,
    "concerns": concerns
})


response = model.invoke(formatted_prompt)  # Sends the completed structured prompt to Gemini.


print("\n--- MEETING PREPARATION BRIEF ---\n")
print(response.text)  # Displays the meeting preparation advice generated by Gemini.